# Generated by Django 3.2 on 2021-07-31 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='place',
            new_name='city',
        ),
    ]
