# Generated by Django 3.2 on 2021-05-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='is_bad_condition',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
