# Generated by Django 3.2 on 2021-07-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_productimage_first_imgsave'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='first_imgsave',
            field=models.BooleanField(default=False),
        ),
    ]
