# Generated by Django 3.2 on 2021-07-30 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productimage_first_imgsave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='first_imgsave',
        ),
    ]
