# Generated by Django 3.2 on 2021-07-31 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_first_imgsave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='first_imgsave',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='first_imgsave',
        ),
    ]
